    - name: Install Apache and PHP
      tags: apache,apache2,ubuntu
      apt:
        name:
          - "{{ apache_pack }}"
          - "{{ php_pack }}"
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache and PHP (CentOS)
      tags: apache,centos
      yum:
        name:
          - "{{ apache_pack }}"
          - "{{ php_pack }}"
        state: latest
      when: ansible_distribution == "CentOS"

    - name: change in email line
      tags: apache,centos,httpd
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^ServerAdmin'
        line: serveradmin dany@some.net
      when: ansible_distribution == "CentOS"
      notify: restart_httpd


    - name: Copy html file
      tags: apache,apache2,ubuntu
      copy:
        src: de_ht.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: "0644"
      when: ansible_distribution == "Ubuntu"

    - name: Restart apache service
      tags: apache,ubuntu,apache2
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
