- name: add ssh key for syam
  tags: always
  authorized_key:
    user: syam
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHDXIG7572ONxHf7NryT9Ju/OWlg1vKPG5nn80mcANIi ansible"
 
- name: Generating ssh_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: restart sshd
